apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jwhj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pvjp-tenant/rhtap-demo-app/hacbs-test-project-jwhj@sha256:71187c27e7259a500d7a6c22866aad5fade76b620af6cba98f011fd841f51d91
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
