apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jwhj
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pvjp-tenant/rhtap-demo-app/hacbs-test-project-jwhj@sha256:1ee8a12e3046263be6c7b9f60bbb8a7ddd3f14483df99cd79f82609b07b7e786
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
